### ISSUE TITLE
[MongodbRepository] - public/protected access to morphia object

### ISSUE THREAD

**Issue by fa-at-pulsit** [RestExpress/RepoExpress#22]
Hi, 
in my pull request i have added public method for morphia object, I understand, that it against idea to make restexpress compatible and easy to switch between different databases. For small queries its perfect but not for advanced. I do mostly project with mongodb, with complicated queries and aggreagation pipelines, and it's realy  hard (almost impossible) to do this over restexpress api.  And for all this actions, and actions like .map() after aggregation I need a morphia object. Other solution, for example, it's possible to set local variable morphia (in MongodbRepository) to protected..... After that I can extends my implementation of MongodbRepository. 
What do you think about it ?

**Comment by tfredrich** [comment]
Merged. Thanks!
